name: Build RustDesk Windows Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code + submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install vcpkg dependencies (manifest mode)
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install
        shell: powershell

      - name: Build
        run: cargo build --release --package rustdesk
        env:
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
