name: Build RustDesk Windows Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout source code + submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install vcpkg and opus
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install opus:x64-windows-static
        shell: powershell

      - name: Build RustDesk Client
        run: cargo build --release --package rustdesk


