name: Build RustDesk Windows Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code + submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
        shell: powershell

      - name: Install dependencies (manifest mode)
        run: .\vcpkg\vcpkg install --triplet x64-windows-static
        shell: powershell
        env:
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg

      - name: Build RustDesk client
        run: cargo build --release --package rustdesk
        shell: powershell
        env:
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
